### ISSUE TITLE
типи даних

### ISSUE THREAD

**Issue by pecourses** [ArtyomHloba/first-express-app#1]
https://github.com/ArtyomHloba/first-express-app/blob/420618b78bdc1c83b74eda01c756ce7ce5711a7b/controllers/tasksController.js#L36
https://github.com/ArtyomHloba/first-express-app/blob/420618b78bdc1c83b74eda01c756ce7ce5711a7b/controllers/tasksController.js#L52
https://github.com/ArtyomHloba/first-express-app/blob/420618b78bdc1c83b74eda01c756ce7ce5711a7b/controllers/tasksController.js#L67
- `id`, яке згенероване `uuid` - рядок, в `params` з запиту приходе також завжди рядок, тому їх можна порівнювати за допомого `===`. Тjму, щоб не робити додаткові перевірки з перетворенням на тип `number`, можна `id` першої, тестової таски зробити рядком: `'1'`

**Comment by ArtyomHloba** [comment]
Фиксанул
